### ISSUE TITLE
Processing does not seem fully up to date with QGIS repo 2.18 branch

### ISSUE THREAD

**Issue by radosuav** [TIGER-NET/WOIS_processing#14]
For example we have 11 files in [core](https://github.com/DHI-GRAS/ESA_Processing/tree/master/core), while in [QGIS 2.18 branch](https://github.com/qgis/QGIS/tree/release-2_18/python/plugins/processing/core) there are 14 files.

**Comment by j08lue** [comment]
Very well spotted, @radosuav . There was a faulty `.gitignore` that prevented a very odd selection of files to be tracked by git. Weird.

I completely removed `.gitignore` and added the remaining files, so now `meld` is telling me QGIS processing and ESA_Processing are identical.

![image](https://cloud.githubusercontent.com/assets/3404817/22787870/104efaa0-eede-11e6-878c-d22d965cffd3.png)

Pls close if you agree.

**Comment by j08lue** [comment]
GRASS 6 is now enabled after installation with https://github.com/TIGER-NET/WOIS_plugins/commit/9bb07467678d1d9cf953e5a984572fb72476a9a1. Closing this.
