### ISSUE TITLE
notice on r.mapcalculator

### ISSUE THREAD

**Issue by ctottrup** [TIGER-NET/WOIS_processing#4]
In QGIS 2.2 quotation marks should be removed when using more complex statements

**Comment by radosuav** [comment]
This applies to all text inputs to GRASS algorithms. Therefore workflows should be updated to remove any present quotation marks.

Example:
Incorrect:
![incorrect](https://cloud.githubusercontent.com/assets/4759850/3372600/5d7a7642-fbac-11e3-8554-14e2e0e355f8.png)
Correct:
![incorrect](https://cloud.githubusercontent.com/assets/4759850/3372630/933e7364-fbac-11e3-8049-695928659fe5.png)

**Comment by radosuav** [comment]
All workflows should now be updated.
