### ISSUE TITLE
Missing Text-files

### ISSUE THREAD

**Issue by Somcar** [TIGER-NET/WOIS_processing#7]
In Product Group #06: Water body mapping, when executing the Workflow Water body mapping – optical based, there are filter files (.txt files) required in several steps. 
For example in Step 8 and 10, step 13 and 14.

It says that the filter file is optional, however the steps cannot be run without the filter file, an error occurs, which says that the filter file was not found.

Where can I find the mentioned .txt files? I couldn’t find them on the WOIS webpage or in the download area. Which folder is meant by “Input_data folder”?

**Comment by radosuav** [comment]
The filter files have been added to the Workflows directory in this commit: https://github.com/TIGER-NET/Processing-Workflow/commit/bff612759c1626c293ffcc39141efd8691ef8350
