### ISSUE TITLE
How to update WOIS

### ISSUE THREAD

**Issue by Somcar** [TIGER-NET/WOIS_processing#8]
Hello,
how can I update WOIS to the latest version? I already copied the latest scripts and models to the ".qgis2/processing/" directory. But if i want to move the folder "workflows" to the .qgis2/processing/workflows directory, nothing happens. I already changed the "Workflow algorithms folder" path in QGIS 2.12.2 in the processing options for WOIS Workflows. But when I do that, I can't see any workflows at all in the WOIS plugin. What else do I have to do? How do the paths have to look like? And what should I do with the GitHub folder "WOIS_Processing-master"? 

Thanks in advance.

**Comment by radosuav** [comment]
Hi,
We are in the process of preparing for the next major release of WOIS and therefore the code on GitHub might not currently be stable and cannot be used for simple upgrading. However, we have also prepared a minor release (3.0.2) which should be available for download from ESA TIGER web page (http://www.tiger.esa.int/page_eoservices_wois_form.php) soon. This minor release contains most of the changes and fixes from GitHub that are compatible with current WOIS components (i.e. QGIS 2.8 and S1TBX 1.1.1). We will let you know once it is out.

The major release of WOIS will contain the QGIS 2.14 and SNAP 2.0 (replacing S1TBX) and other developments and should become available in the weeks after QGIS 2.14 is out at the end of February.

**Comment by radosuav** [comment]
The minor release is now available from the ESA TIGER web page.
